### ISSUE TITLE
jwks

### ISSUE THREAD

**Issue by TrejGun** [jusbid/nestjs#1]
Hello

i have reviewed your code and did not find how you use 
https://www.googleapis.com/oauth2/v3/certs

please rework

**Comment by jusbid** [comment]
committed new code in nodejs only, because currently not familiar with nestjs, need to learn and work on it,   to use this https://www.googleapis.com/oauth2/v3/certs for checking whether jwt token is valid or not, need to work on it to find a solution but currently used this "passport-google-plus-token" which is verifying and providing user profile data which is logged in console after passing access token as request param it provides user profile data....if requirement is not fulfilled please guide, thanks.............
